# .readthedocs.yaml
# Read the Docs configuration file

# Required
version: 2

# Set the version of Python 
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the docs/directory with Sphinx
sphinx:
   configuration: docs/conf.py

#formats:
#    - pdf

# Python requirements
python:
  install:
  - requirements: requirements.txt